In [58]:
#Obtener coeficientes de las matrices

import numpy as np
#import simpy as sp
#from simpy import Matrix

h = int(input('Escribe un valor para h: '))
x0 = int(input('Escribe un valor para x: '))
matrizD = np.array([[1, 1, 1, 0], [0, 1, 2, 1/h], [0, 1, 4, 0]])
#print(matriz)
matrizD[2] = matrizD[2] - matrizD[1] 

matrizD[2] = matrizD[2]/2
matrizD[0] = matrizD[0] - matrizD[2]
matrizD[1] = matrizD[1] - 2*matrizD[2]
matrizD[0] = matrizD[1] - matrizD[0]
print(matrizD)


for fila in matrizD:
    print(fila[-1])
 
    
matrizd = np.array([[1, 1, 1, 0], [0, 1, 2, -1/h], [0, 1, 4, 0]])
#print(matriz)
matrizd[2] = matrizd[2] - matrizd[1] 

matrizd[2] = matrizd[2]/2
matrizd[0] = matrizd[0] - matrizd[2]
matrizd[1] = matrizd[1] - 2*matrizd[2]
matrizd[0] = matrizd[1] - matrizd[0]
print(matrizd)   

for fila in matrizd:
    print(fila[-1])

Escribe un valor para h: 3
Escribe un valor para x: 5
[[-1.          0.          0.          0.5       ]
 [ 0.          1.          0.          0.66666667]
 [ 0.          0.          1.         -0.16666667]]
0.5
0.6666666666666666
-0.16666666666666666
[[-1.          0.          0.         -0.5       ]
 [ 0.          1.          0.         -0.66666667]
 [ 0.          0.          1.          0.16666667]]
-0.5
-0.6666666666666666
0.16666666666666666


In [59]:
#x0 = 1
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def D_menos(u,x,h):
    return ((matrizd[0][-1]*(x0)) + matrizd[1][-1]*(x0-h) - matrizd[2][-1]*(x0-2*h)) 

def D_max (u,x,h):
    return ((-matrizD[0][-1]*(x0)) - matrizD[1][-1]*(x0-h) + matrizD[2][-1]*(x0-2*h)) 
print((-matrizD[0][-1]*(x0)) - matrizD[1][-1]*(x0-h) + matrizD[2][-1]*(x0-2*h)) 
print((matrizd[0][-1]*(x0)) + matrizd[1][-1]*(x0-h) - matrizd[2][-1]*(x0-2*h))

-3.6666666666666665
-3.6666666666666665


In [60]:
edmi = np.fabs( np.cos(x0) - D_menos(np.sin,x0,h) )
edmax = np.fabs( np.cos(x0) - D_max(np.sin,x0,h) )
print(edmax)
print(edmi)
# Metemos la información de h y del error en un Dataframe y mostramos el resultado:
#Error = pd.DataFrame(np.array([edmi, edmax]).transpose(), columns=[['$D_-$', '$D_+$']])
#Error


3.9503288521298927
3.9503288521298927
